_webservice_call:
  pattern: "/soap/{webservice}"
  defaults:
    _controller: SmartboxApiBundle:Soap:Call
    _format: xml
    api: soap

  requirements:
    _method: POST

_webservice_definition:
  pattern: "/soap/{webservice}"
  defaults:
    _controller: SmartboxApiBundle:Soap:Definition
    _format: xml
    api: soap

  requirements:
    _method: GET

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
    defaults:
      api: doc