_webservice_call:
  path: "/soap/{webservice}"
  defaults:
    _controller: SmartboxApiBundle:Soap:Call
    _format: xml
    api: soap
  methods: [POST]

_webservice_definition:
  path: "/soap/{webservice}"
  methods: [GET]
  defaults:
    _controller: SmartboxApiBundle:Soap:Definition
    _format: xml
    api: soap

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
    defaults:
      api: doc