parameters:
  # OVERRIDING RATELIMIT
  noxlogic_rate_limit.rate_limit_annotation_listener.class: Smartbox\ApiBundle\EventListener\ThrottlingListener

services:
    noxlogic_rate_limit.rate_limit_annotation_listener:
        class: %noxlogic_rate_limit.rate_limit_annotation_listener.class%
        arguments:
            - @event_dispatcher
            - @noxlogic_rate_limit.rate_limit_service
            - @noxlogic_rate_limit.path_limit_processor
        calls:
            - [ setParameter, ["rate_response_code", "%noxlogic_rate_limit.rate_response_code%"] ]
            - [ setParameter, ["rate_response_message", "%noxlogic_rate_limit.rate_response_message%"] ]
            - [ setParameter, ["rate_response_exception", "%noxlogic_rate_limit.rate_response_exception%"] ]
        tags:
            - { name: "kernel.event_listener", event: "kernel.controller", method: "onKernelController", priority: "-10" }

    smartapi.event_listener.auth_key_generator:
        class: %smartapi.event_listener.auth_key_generator.class%
        arguments: [@?security.token_storage]
        tags:
            - { name: kernel.event_listener, event: ratelimit.generate.key, method: onGenerateKey }