parameters:
  # OVERRIDING RATELIMIT
  smartapi.throttling_listener.class: Smartbox\ApiBundle\EventListener\ThrottlingListener

services:
    smartapi.event_listener.auth_key_generator:
        class: %smartapi.event_listener.auth_key_generator.class%
        arguments: [@?security.token_storage]
        tags:
            - { name: kernel.event_listener, event: ratelimit.generate.key, method: onGenerateKey }