image: docker-registry.production.smartbox.com/eai/bifrostqa

services:
#  - redis
#  - mysql:5.7.16
#  - docker-registry.production.smartbox.com/eai/rabbitmq-stomp

variables:
#  AUTH: "no"
#  MOCKS_ENABLED: "true"
#  MYSQL_ROOT_PASSWORD: "12345"
#  MYSQL_DATABASE: "eai"
#  MERGE_REQUEST_TARGET_BRANCH: "bau"
#  SKIP_CHECKOUT_DEPENDENCIES: "false" # "true" of "false"
  GIT_STRATEGY: clone
#  RABBITMQ_HOST: "docker-registry.production.smartbox.com-eai-rabbitmq-stomp"

before_script:
  - composer self-update
  # Prevents commands with | to display an error message in Gitlab CI (tput: No value for $TERM and no -T specified)
  - export TERM=dumb
  # make sure we have the ssh-agent running
  - eval $(ssh-agent -s)
  # Configure docker based on the ENV variables
  - bash ci/docker_env_init.sh
  # configure app (check script for credentials and settings)
#  - bash ci/setup_parameters_yml.sh
  # install dependencies with .git information (prefer-source)
  - composer install --prefer-source
  # checkout same branch dependencies if they exist
#  - bash ci/checkout_dependencies.sh
  # install DB Schema
#  - php app/console doctrine:schema:update --force
  # Clearing RabbitMq Queues for gitlab_ci user
#  - bash ci/clear_gitlab_ci_rabbitmq.sh

cache:
  key: ${CI_BUILD_REF_NAME}-1
  paths:
  - vendor/

test:app:
  script:
#    -  bin/mocks-checking
    -  bin/phpunit --colors --debug --coverage-text
