services:
  - redis

variables:
  GIT_STRATEGY: clone

stages:
  - test

cache:
  paths:
  - vendor/
  - bin/

before_script:
  - composer-install

PHP7:
  stage: test
  image: docker-registry.production.smartbox.com/ci/php:7.0
  script:
    -  bin/simple-phpunit --coverage-text --colors=never

PHP71:
  stage: test
  image: docker-registry.production.smartbox.com/ci/php:7.1
  script:
    -  bin/simple-phpunit --coverage-text --colors=never

PHP72:
  stage: test
  image: docker-registry.production.smartbox.com/ci/php:7.2
  script:
    -  bin/simple-phpunit --coverage-text --colors=never

coding-standards:
  stage: test
  image: docker-registry.production.smartbox.com/mint/php:7.2-cli
  before_script: []
  script:
  - php-cs-fixer --version
  - php-cs-fixer fix --verbose --rules=@Symfony --dry-run --using-cache=no
