services:
  - redis

variables:
  GIT_STRATEGY: clone

before_script:
  - composer-install

cache:
  paths:
  - vendor/

test:PHP56:
  image: docker-registry.production.smartbox.com/ci/php:56
  script:
    -  bin/simple-phpunit --coverage-text --colors=never

test:PHP70:
  image: docker-registry.production.smartbox.com/ci/php:70
  script:
    -  bin/simple-phpunit --coverage-text --colors=never

test:PHP72:
  image: docker-registry.production.smartbox.com/ci/php:72
  script:
    -  bin/simple-phpunit --coverage-text --colors=never