image: docker-registry.production.smartbox.com/ci/php:56

services:
  - redis

variables:
  GIT_STRATEGY: clone

before_script:
  - composer-install

cache:
  paths:
  - vendor/

test:PHP56:
  script:
    -  bin/phpunit --debug --coverage-text
