services:
  - redis

variables:
  GIT_STRATEGY: clone
  SYMFONY_PHPUNIT_VERSION: '6.5'

stages:
  - test

cache:
  paths:
  - vendor/
  - bin/

before_script:
  - composer-install

PHP7:
  stage: test
  image: docker-registry.production.smartbox.com/mint/php:7.0-cli
  script:
    -  bin/simple-phpunit

PHP71:
  stage: test
  image: docker-registry.production.smartbox.com/mint/php:7.1-cli
  script:
    -  bin/simple-phpunit

PHP72:
  stage: test
  image: docker-registry.production.smartbox.com/mint/php:7.2-cli
  script:
    -  bin/simple-phpunit --coverage-text --colors=never

coding-standards:
  stage: test
  image: docker-registry.production.smartbox.com/mint/php:7.2-cli
  before_script: []
  script:
  - php-cs-fixer --version
  - php-cs-fixer fix --verbose --rules=@Symfony --dry-run --using-cache=no
