language: php

php:
  - '7.3'

matrix:
  allow_failures:
    - php: '7.3'

env:
  - SYMFONY_VERSION=3.4.* SYMFONY_PHPUNIT_VERSION=6.5

before_install:
  - phpenv config-add travis/z_php.ini
  - composer self-update

before_script:
  - echo $TRAVIS_PHP_VERSION
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --no-interaction
  - composer require friendsofphp/php-cs-fixer

script:
  - vendor/bin/php-cs-fixer fix --verbose --rules=@Symfony --dry-run --using-cache=no
  - SYMFONY_PHPUNIT_VERSION=6.5 SYMFONY_DEPRECATIONS_HELPER=417 bin/simple-phpunit --coverage-text # TODO: Fix deprecations

notifications:
  email:
    recipients:
      - si-integration@smartandco.com
    on_success: change
    on_failure: always

services:
  - redis
