version: '3'
services:
  app:
    build: .
    image: smartbox/apibundle
    container_name: sbx_apibundle
    environment:
      SYMFONY_PHPUNIT_VERSION: '6.5'
      COMPOSER_ALLOW_SUPERUSER: 1
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:rw