version: '3'

services:
  redis:
    image: redis:alpine
  app:
    image: docker-registry.production.smartbox.com/mint/php:7.0-cli
    environment:
      SYMFONY_PHPUNIT_VERSION: '6.5'
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - redis